export enum CheckpointKey {
  DEMONSTROU_INTERESSE = 'DEMONSTROU_INTERESSE',
  PEDIU_PROPOSTA = 'PEDIU_PROPOSTA',
  AGENDOU_REUNIAO = 'AGENDOU_REUNIAO',
  ORCAMENTO_ALINHADO = 'ORCAMENTO_ALINHADO',
  DECISOR_ENVOLVIDO = 'DECISOR_ENVOLVIDO',
  URGENCIA_PRAZO = 'URGENCIA_PRAZO',
}

export const CHECKPOINT_POINTS: Record<CheckpointKey, number> = {
  [CheckpointKey.DEMONSTROU_INTERESSE]: 15,
  [CheckpointKey.PEDIU_PROPOSTA]: 20,
  [CheckpointKey.AGENDOU_REUNIAO]: 20,
  [CheckpointKey.ORCAMENTO_ALINHADO]: 15,
  [CheckpointKey.DECISOR_ENVOLVIDO]: 15,
  [CheckpointKey.URGENCIA_PRAZO]: 15,
};
