export enum LeadStage {
  LEAD = 'LEAD',
  CONTATADO = 'CONTATADO',
  PROPOSTA = 'PROPOSTA',
  REUNIAO = 'REUNIAO',
  FECHADO = 'FECHADO',
  ENTREGA = 'ENTREGA',
  PAGO = 'PAGO',
  PERDIDO = 'PERDIDO',
}
